Elasticsearch Plugin
arcalot/arcaflow-plugin-elasticsearch pull request #1
Opened 2022-10-11 15:47 UTC by mfleader

## Changes introduced with this PR

Load data into an elasticsearch instance.

---
By contributing to this repository, I agree to the [contribution guidelines](https://github.com/arcalot/.github/blob/main/CONTRIBUTING.md).

2022-10-12 09:31 UTC, sandrobonazzola requested changes
Inline comments

2022-10-12 09:31 UTC, sandrobonazzola commented on pyproject.toml
> +version = "0.1.0"
you can set this to `"0.0.0"` and have github action updating this on tagged build.
See: https://github.com/arcalot/arcaflow-plugin-sdk-python/blob/main/pyproject.toml#L8
and https://github.com/arcalot/arcaflow-plugin-sdk-python/blob/main/.github/workflows/build.yml#L60

2022-10-12 09:31 UTC, sandrobonazzola commented on es_plugin.py
> +    )))
missing new line at EOF

2022-10-12 09:31 UTC, sandrobonazzola commented on es_plugin.py
> +        pass
looks like the implementation is missing :-)

2022-10-12 09:31 UTC, sandrobonazzola commented on Dockerfile
> +LABEL io.github.arcalot.arcaflow.plugin.version="1"
missing new line at EOF

2022-10-12 09:31 UTC, sandrobonazzola commented on .github/workflows/carpenter.yaml
> +          args: build --build --push
missing new line at EOF

2022-10-12 15:17 UTC, portante commented on es_schema.py
> +            'name': 'data',
Lots of questions come up with this plug-in.

Typically one does not just index one document into Elasticsearch.  You have a series of N documents that you want indexed.  So while this is fine for an initial step, we need to discuss the nature of this as a plugin.

FWIW, we wrote [pyesbulk](https://pypi.org/project/pyesbulk/) to enable an efficient way of indexing a stream of data into Elasticsearch, with error handling, and able to handle multiple documents.

It is primarily used by the [pbench server code](https://github.com/distributed-system-analysis/pbench/blob/665132a898e068a6c488610ccc447fd33db68035/lib/pbench/server/indexer.py#L180).

2022-10-12 15:48 UTC, ghost commented on es_schema.py
> +            'name': 'data',
We don't have data streams in Arcaflow yet, hence we need to call one by one. Once streams are supported we can consider adding that support.

2022-10-12 18:27 UTC, portante commented on es_schema.py
> +            'name': 'data',
One document at a time isn't going to be worth it in a workflow, you'll either have a huge scaling problem trying to describe all the individual documents in the workflow, or you'll have too large a document to be useful in Elasticsearch.

2022-10-17 16:55 UTC, closed without merging

2022-10-17 20:17 UTC, portante commented
Having a reason for closing a PR with unresolved conversations would be helpful.  Is this because it is superseded by #2?