initial function with opensearch
arcalot/arcaflow-plugin-elasticsearch pull request #11
Opened 2022-11-22 15:01 UTC by dustinblack

## Changes introduced with this PR

The python elasticsearch module had some compatibility issues, so this has been changed to the opensearch module. There is also a feature added to enable auth-free connection to an ES server, and the url, username, and password values have been changed to direct input instead of environment variable references.

A proper approach to the authentication mechanism needs to be implemented before we push this forward.

---
By contributing to this repository, I agree to the [contribution guidelines](https://github.com/arcalot/.github/blob/main/CONTRIBUTING.md).

2022-11-22 15:58 UTC, jaredoconnell commented
Does the opensearch library work properly with ElasticSearch 8?

2022-11-24 01:37 UTC, portante requested changes

2022-11-24 01:37 UTC, portante commented on es_schema.py
> +            "description": """The URL for the Elasticsearch instance.""",
Do we want to use OpenSearch here?  And if so, rename the plugin, too?

2022-11-24 01:37 UTC, portante commented on es_plugin.py
Is there a reason why we dropped the response code check for `201`?

2023-01-09 16:59 UTC, closed without merging